spring:
  application:
    name: reactive-load-test
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      platform: postgres
      mode: always
server:
  port: 8084
